# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-23 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_wall', '0005_comment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsm', to='my_wall.Message'),
        ),
    ]
