# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-24 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_wall', '0006_auto_20190323_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.IntegerField(),
        ),
    ]
