# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-24 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_wall', '0007_auto_20190324_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='message_id',
        ),
    ]
