# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-25 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_wall', '0008_auto_20190324_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentsm', to='my_wall.User'),
            preserve_default=False,
        ),
    ]
